CREATE DATABASE beecrowd3480;
USE beecrowd3480;

CREATE TABLE chairs (
	id SMALLINT AUTO_INCREMENT PRIMARY KEY,
    queue SMALLINT NOT NULL,
    available BOOLEAN NOT NULL
);

BEGIN;
INSERT INTO chairs VALUES (1, 1, FALSE); -- poderia inserir default por causa do AUTO_INCREMENT, ou ocultar completamente definindo quais colunas tais atributos estão sendo inseridos
INSERT INTO chairs VALUES (2, 1, FALSE);
INSERT INTO chairs VALUES (3, 1, TRUE);
INSERT INTO chairs VALUES (4, 1, FALSE);
INSERT INTO chairs VALUES (5, 1, FALSE);
INSERT INTO chairs VALUES (6, 1, FALSE);
INSERT INTO chairs VALUES (7, 1, TRUE);
INSERT INTO chairs VALUES (8, 1, TRUE);
INSERT INTO chairs VALUES (9, 2, TRUE);
INSERT INTO chairs VALUES (10, 2, FALSE);
INSERT INTO chairs VALUES (11, 2, TRUE);
INSERT INTO chairs VALUES (12, 2, TRUE);
INSERT INTO chairs VALUES (13, 2, FALSE);
INSERT INTO chairs VALUES (14, 2, TRUE);
INSERT INTO chairs VALUES (15, 2, TRUE);
INSERT INTO chairs VALUES (16, 2, FALSE);
INSERT INTO chairs VALUES (17, 3, TRUE);
INSERT INTO chairs VALUES (18, 3, FALSE);
INSERT INTO chairs VALUES (19, 3, TRUE);
INSERT INTO chairs VALUES (20, 3, FALSE);
INSERT INTO chairs VALUES (21, 3, TRUE);
INSERT INTO chairs VALUES (22, 3, TRUE);
INSERT INTO chairs VALUES (23, 3, FALSE);
INSERT INTO chairs VALUES (24, 3, FALSE);
INSERT INTO chairs VALUES (25, 4, TRUE);
INSERT INTO chairs VALUES (26, 4, FALSE);
INSERT INTO chairs VALUES (27, 4, FALSE);
INSERT INTO chairs VALUES (28, 4, TRUE);
INSERT INTO chairs VALUES (29, 4, TRUE);
INSERT INTO chairs VALUES (30, 4, FALSE);
INSERT INTO chairs VALUES (31, 4, FALSE);
INSERT INTO chairs VALUES (32, 4, TRUE);

ROLLBACK;

SELECT * FROM chairs;


2	1	FALSE
3	1	TRUE
4	1	FALSE
5	1	FALSE
6	1	FALSE
7	1	TRUE
8	1	TRUE
9	2	TRUE
10	2	FALSE
11	2	TRUE
12	2	TRUE
13	2	FALSE
14	2	TRUE
15	2	TRUE
16	2	FALSE
17	3	TRUE
18	3	FALSE
19	3	TRUE
20	3	FALSE
21	3	TRUE
22	3	TRUE
23	3	FALSE
24	3	FALSE
25	4	TRUE
26	4	FALSE
27	4	FALSE
28	4	TRUE
29	4	TRUE
30	4	FALSE
31	4	FALSE
32	4	TRUE